# Generated by Django 2.1.7 on 2019-03-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='hash_id',
            field=models.CharField(blank=True, max_length=6, primary_key=True, serialize=False, unique=True),
        ),
    ]
