# Generated by Django 2.1.7 on 2019-04-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
