# Generated by Django 2.1.7 on 2019-04-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20190402_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
